# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://1661691223.github.io
date_format: "ordinal"
title: rui123672
subtitle: "程序码"
description: "rui123672的个人博客"
keywords: rui123782, Du Rui, shell
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: rui123672
organization: ZStack
organization_url: http://zstack.io
github_username: rui123672
location: Shanghai, China
email: rui123672@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: 1661691223/1661691223.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 1661691223
    repo: 1661691223.github.io
    oauth:
        client_id: 1bacdc436c1f331547ed
        client_secret: d707db7daf552056b7cea5f84eec900a368a0581
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 1661691223
    repo: 1661691223.github.io
    clientID: 1bacdc436c1f331547ed
    clientSecret: d707db7daf552056b7cea5f84eec900a368a0581
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

theme: jekyll-theme-leap-day
